<a href="https://colab.research.google.com/github/varunegit/carisurg-portfolio/blob/main/Tutorial1_Week0_CariSurg.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
from google.colab import drive
drive.mount('/content/drive')
print("Drive mounted successfully!")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Drive mounted successfully!

In [14]:
import sys
print(f"Python version: {sys.version}")

Python version: 3.12.13 (main, Mar  4 2026, 09:23:07) [GCC 11.4.0]

In [15]:
import pandas as pan
import numpy as py
import matplotlib.pyplot as plt

FILE_PATH = '/content/drive/MyDrive/Colab Notebooks/EmergencyTriageDataset_Reduced_Dirty.csv'

df = pan.read_csv(FILE_PATH)
df.head(11)

    ID  Age  Gender   GCS  SBP    DBP     MAP  pulse  Temp    RR   Fio2
0    1   34       0  15.0   93   67.0   75.67  128.0  36.8  14.0   21.0
1    2   20    Male  15.0  130   90.0  103.33   80.0  37.0  16.0   21.0
2    3   77  Female  14.0  163  105.0  124.33   92.0  36.8  18.0   21.0
3    4   23       0   8.0  100   60.0   73.33  100.0  37.0  12.0  100.0
4    5   86  FEMALE  15.0  150   90.0  110.00   85.0  37.0  19.0   21.0
5    6   42    Male  15.0  100   60.0   73.33   99.0  37.0  20.0   21.0
6    7   75  Female  15.0  120   80.0   93.33   99.0  37.0  25.0   21.0
7    8   25    Male  15.0  100   50.0   66.67   85.0  37.0  25.0   21.0
8    9   67       0  15.0  110   70.0   83.33   78.0  37.0  16.0   21.0
9   11   82  Female  15.0  153   82.0  105.67  130.0  37.0  19.0   21.0
10  12   78       0  15.0  150   90.0  110.00   85.0  37.0  16.0   21.0

In [16]:
print(df.dtypes)

ID          int64
Age         int64
Gender     object
GCS        object
SBP        object
DBP       float64
MAP       float64
pulse      object
Temp       object
RR        float64
Fio2      float64
dtype: object

In [41]:
#Standardizing the elements to lowercase to map fewer elements
df['Gender'] = df['Gender'].astype(str)
df['Gender'] = df['Gender'].str.strip().str.lower()
print(f"\nValues in .lower() Gender Column: {df['Gender'].unique()} Total unique values: {df['Gender'].nunique()}")

#Setting up the map for every variant of Gender
genderMap = {
    'male': 1,
    '1': 1,
    'female':0,
    '0': 0
}

#Replace the intial gender column with the cleaned column
df['Gender'] = df['Gender'].map(genderMap)
print(f"\nCleaned Gender Column {df['Gender'].value_counts()}")

Nan = df['Gender'].isnull().sum()
if(Nan>0):
    print("Nan values detected!")

else:
  print("\nNo NaN detected")

#Print to see results
df.head()

Values in .lower() Gender Column: ['0' '1'] Total unique values: 2

Cleaned Gender Column Gender
1    1176
0    1029
Name: count, dtype: int64

No NaN detected

,ID,Age,Gender,GCS,SBP,DBP,MAP,pulse,Temp,RR,Fio2,CleanColumn
0,1,34,0,15.0,93,67.0,75.67,128.0,36.8,14.0,21.0,0
1,2,20,1,15.0,130,90.0,103.33,80.0,37.0,16.0,21.0,1
2,3,77,0,14.0,163,105.0,124.33,92.0,36.8,18.0,21.0,0
3,4,23,0,8.0,100,60.0,73.33,100.0,37.0,12.0,100.0,0
4,5,86,0,15.0,150,90.0,110.00,85.0,37.0,19.0,21.0,0